<a href="https://colab.research.google.com/github/chimaze12/hamoyetest/blob/master/Hamoye_Linear_Reg_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
raw_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv')

In [ ]:
raw_data= raw_data.drop(['date', 'lights'], axis=1)

In [ ]:
raw_data

       Appliances         T1       RH_1  ...  Tdewpoint        rv1        rv2
0              60  19.890000  47.596667  ...   5.300000  13.275433  13.275433
1              60  19.890000  46.693333  ...   5.200000  18.606195  18.606195
2              50  19.890000  46.300000  ...   5.100000  28.642668  28.642668
3              50  19.890000  46.066667  ...   5.000000  45.410389  45.410389
4              60  19.890000  46.333333  ...   4.900000  10.084097  10.084097
...           ...        ...        ...  ...        ...        ...        ...
19730         100  25.566667  46.560000  ...  13.333333  43.096812  43.096812
19731          90  25.500000  46.500000  ...  13.300000  49.282940  49.282940
19732         270  25.500000  46.596667  ...  13.266667  29.199117  29.199117
19733         420  25.500000  46.990000  ...  13.233333   6.322784   6.322784
19734         430  25.500000  46.600000  ...  13.200000  34.118851  34.118851

[19735 rows x 27 columns]

In [ ]:
df=raw_data

In [ ]:
 from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
scaled_data= pd.DataFrame(scaler.fit_transform(df), columns= df.columns)
scaled_data

       Appliances        T1      RH_1  ...  Tdewpoint       rv1       rv2
0        0.046729  0.327350  0.566187  ...   0.538462  0.265449  0.265449
1        0.046729  0.327350  0.541326  ...   0.533937  0.372083  0.372083
2        0.037383  0.327350  0.530502  ...   0.529412  0.572848  0.572848
3        0.037383  0.327350  0.524080  ...   0.524887  0.908261  0.908261
4        0.046729  0.327350  0.531419  ...   0.520362  0.201611  0.201611
...           ...       ...       ...  ...        ...       ...       ...
19730    0.084112  0.926786  0.537657  ...   0.901961  0.861981  0.861981
19731    0.074766  0.919747  0.536006  ...   0.900452  0.985726  0.985726
19732    0.242991  0.919747  0.538666  ...   0.898944  0.583979  0.583979
19733    0.383178  0.919747  0.549491  ...   0.897436  0.126371  0.126371
19734    0.392523  0.919747  0.538758  ...   0.895928  0.682391  0.682391

[19735 rows x 27 columns]

In [ ]:
x= pd.DataFrame(scaled_data['T2'])
y= pd.DataFrame(scaled_data['T6'])

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train,y_test= train_test_split(x, y, test_size=0.3, random_state=42)

9129     0.122850
2453     0.188999
9152     0.057427
12694    0.280834
16952    1.000000
           ...
11284    0.239157
11964    0.428883
5390     0.152653
860      0.315047
15795    0.275503
Name: T2, Length: 13814, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression

linear_mod= LinearRegression()
fitted_mod=linear_mod.fit(x_train,y_train)

In [ ]:
predicted=linear_mod.predict(x_test)
predicted

array([[0.23928945],
       [0.46794238],
       [0.23108472],
       ...,
       [0.3001772 ],
       [0.4297256 ],
       [0.3217686 ]])

In [ ]:
from sklearn.metrics import r2_score
r_squared= r2_score(y_test, predicted)
round(r_squared,2)

0.64

In [ ]:
from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_test,predicted)
round(mae, 2)

0.08

In [ ]:
rss=np.sum(np.square(y_test-predicted))
round(rss,2)

T6    66.12
dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error
RMSE= np.sqrt(mean_squared_error(y_test,predicted))
round(RMSE,3)

0.106

In [ ]:
def get_weights(model, feat, col_names):
  weights=pd.Series(model.coef_, index=feat.columns).sort_values()
  weights_df=pd.DataFrame(weights).reset_index()
  weights_df.columns= ['Features', col_names]
  return weights_df

In [31]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

ridge= Ridge(alpha= 0.5)
ridge.fit(x_train,y_train)
ridge_reg= get_weights(ridge ,x_train, 'Ridge_weights')

ridge_reg

Exception: ignored